# Generated by Django 4.2.11 on 2025-11-03 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotesPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("thumbnail_src", models.URLField(blank=True)),
                ("thumbnail_dark_src", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_pages",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notes Page",
                "verbose_name_plural": "Notes Pages",
                "ordering": ("course", "order_index"),
            },
        ),
        migrations.CreateModel(
            name="NotesShape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shapes",
                        to="notes.notespage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notes Shape",
                "verbose_name_plural": "Notes Shapes",
                "ordering": ("page", "version"),
            },
        ),
    ]
