# Generated by Django 4.2.11 on 2025-11-04 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("instructions", models.TextField(blank=True)),
                ("instructions_html", models.TextField(blank=True)),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=100, max_digits=7),
                ),
                ("publish_date_utc", models.DateTimeField(blank=True, null=True)),
                ("publish_date_timezone", models.CharField(blank=True, max_length=64)),
                ("due_date_utc", models.DateTimeField(blank=True, null=True)),
                ("due_date_timezone", models.CharField(blank=True, max_length=64)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "ordering": ("-publish_date_utc", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="AssignmentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_index", models.PositiveIntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FREE_RESPONSE", "Free Response"),
                            ("MULTIPLE_CHOICE", "Multiple Choice"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assignments.assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment Question",
                "verbose_name_plural": "Assignment Questions",
                "ordering": ("assignment", "order_index"),
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("option_text", models.TextField()),
                ("option_html", models.TextField(blank=True)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "order_index",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Multiple Choice Option",
                "verbose_name_plural": "Multiple Choice Options",
                "ordering": ("question", "order_index", "id"),
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("free_response_answer_text", models.TextField(blank=True)),
                ("free_response_answer_html", models.TextField(blank=True)),
                (
                    "assignment_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.assignmentquestion",
                    ),
                ),
                (
                    "multiple_choice_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="assignments.multiplechoiceoption",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "ordering": ("assignment_question", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="SubmissionOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("feedback", models.TextField(blank=True)),
                ("feedback_html", models.TextField(blank=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome",
                        to="assignments.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Outcome",
                "verbose_name_plural": "Submission Outcomes",
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_text", models.TextField()),
                ("question_html", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_choice_questions",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multiple Choice Question",
                "verbose_name_plural": "Multiple Choice Questions",
                "ordering": ("course", "id"),
            },
        ),
        migrations.AddField(
            model_name="multiplechoiceoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="assignments.multiplechoicequestion",
            ),
        ),
        migrations.CreateModel(
            name="FreeResponseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_text", models.TextField()),
                ("question_html", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_response_questions",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Free Response Question",
                "verbose_name_plural": "Free Response Questions",
                "ordering": ("course", "id"),
            },
        ),
        migrations.AddField(
            model_name="assignmentquestion",
            name="free_response_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_links",
                to="assignments.freeresponsequestion",
            ),
        ),
        migrations.AddField(
            model_name="assignmentquestion",
            name="multiple_choice_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_links",
                to="assignments.multiplechoicequestion",
            ),
        ),
        migrations.CreateModel(
            name="AssignmentExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date_utc", models.DateTimeField()),
                ("due_date_timezone", models.CharField(max_length=64)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment Extension",
                "verbose_name_plural": "Assignment Extensions",
                "unique_together": {("assignment", "user")},
            },
        ),
    ]
