# Generated by Django 4.2.11 on 2025-11-04 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotesPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.TextField(blank=True)),
                (
                    "order_index",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="notes/thumbnails/%Y/%m/%d/"
                    ),
                ),
                (
                    "thumbnail_dark",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="notes/thumbnails/dark/%Y/%m/%d/",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_notes_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_pages",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notes Page",
                "verbose_name_plural": "Notes Pages",
                "ordering": ("course", "order_index", "id"),
            },
        ),
        migrations.CreateModel(
            name="WhiteboardSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboard_sessions",
                        to="courses.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboard_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiteboard Session",
                "verbose_name_plural": "Whiteboard Sessions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WhiteboardStroke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("ts", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strokes",
                        to="whiteboard.whiteboardsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whiteboard_strokes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiteboard Stroke",
                "verbose_name_plural": "Whiteboard Strokes",
                "ordering": ("session", "ts"),
            },
        ),
        migrations.CreateModel(
            name="NotesShape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shapes",
                        to="whiteboard.notespage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notes Shape",
                "verbose_name_plural": "Notes Shapes",
                "ordering": ("page", "version", "id"),
            },
        ),
    ]
